export interface Patient {
    id?: string; // Auto-generated by Firestore
    name: string;
    email: string;
    phone: string;
    password?: string; // Only for signup - don't store directly!
    verified: boolean;
    createdAt: firebase.firestore.Timestamp | Date;
    verificationCode?: string;
    codeExpiry?: firebase.firestore.Timestamp | Date;
  }
  
  export interface AuthCredentials {
    email: string;
    password: string;
  }